videotech_homepage:
    path:     /
    defaults: { _controller: VideotechBundle:Default:index }

videotech_new_film:
  path:    /admin/add/film
  defaults: { _controller: VideotechBundle:FilmManager:createFilmPage }

videotech_film:
  path:    /{catName}/{filmName}-{filmId}
  defaults: { _controller: VideotechBundle:FilmManager:displayFilmPage }

videotech_search:
  path:    /search
  defaults: { _controller: VideotechBundle:FilmManager:searchPage }

videotech_update_film:
  path:    /admin/update/film/{Id}
  defaults: { _controller: VideotechBundle:FilmManager:updateFilm }

videotech_delete_film:
  path:    /admin/delete/film/{Id}
  defaults: { _controller: VideotechBundle:FilmManager:deleteFilm }
  
videotech_new_category:
  path:       /admin/add/cat
  defaults: { _controller: VideotechBundle:FilmManager:modalCreateCategory }

videotech_create_film:
  path:    /admin/create/film
  defaults: { _controller: VideotechBundle:FilmManager:createFilm }


videotech_list_category:
  path:       /categories
  defaults: { _controller: VideotechBundle:FilmManager:categoriesPage }

videotech_category:
  path:       /category/{name}
  defaults: { _controller: VideotechBundle:FilmManager:categoryPage }

videotech_nb_film:
  path:       /getNbFilm
  defaults: { _controller: VideotechBundle:FilmManager:nbFilm }

