VideotechBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: VideotechBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
    oneToMany:
      films:
        targetEntity: Film
        mappedBy: category
        cascade: [ persist , remove ]
    lifecycleCallbacks: {  }
